### PR TITLE
Pull upstream 2.16.2

### PR DESCRIPTION
**Pull request by wallinb**
This is primarily to upgrade the latest nsidc Geoserver image from 2.14.1 to 2.16.2. The kartoza image is still actively developed and has made numerous improvements that seem worthwhile pulling in.

Additional changes:

* Added plugins for testing that seem like they would valuable: 

  - wcs2.0 eo extension - provides some new capabilities, most notably coverage timeseries: (https://docs.geoserver.org/latest/en/user/extensions/wcs20eo/index.html)
  - netcdf input
  - netcdf output

* tweaks to circleci config (drop 'v' prefix from tag)

### CODE REVIEW

**Comment by MattF-NSIDC** [comment]
Man it's been a long time since I've looked at this...

Curious, what was the motivation for the circle CI tweaks?

**Comment by MattF-NSIDC** [comment]
I don't even remember this: why do we fork the kartoza repo instead of using the image or creating our own image that inherits from theirs?

**Comment by wallinb** [comment]
I believe the main reason for building our own image was security. Otherwise there are just minor changes on our end (e.g. only install select plugins, instead of all of them).

The circleci/tag tweak was to follow community convention and, maybe, NSIDC convention (using Valkyrie as a model).  Planning to change to a swarm deployment, so looking to unify things as much as possible. Do we have a convention? I am pretty out of the loop so suggestions welcome!

**Comment by MattF-NSIDC** [comment]
> Planning to change to a swarm deployment

Interesting, for performance? I forget what our stack looks like now. If I remember correctly, we have a postgres database container and a geoserver container running on different hosts.

>Do we have a convention? I am pretty out of the loop so suggestions welcome!

Definitely talk to Michael about Garrison for standardizing your docker swarm deployment. Trey developed a tool that's used on Valkyrie for managing clusters of vms with Vagrant (you work on Valkyrie so that's probably old news).

OPINION: I don't like building clusters for individual apps; I'd much rather be deploying many apps to a target cluster that exists as a platform instead of having to do it bespoke for each app. We still don't have that platform available, though, unless we can use a cloud service.

**Comment by wallinb** [comment]
Right now there are two VM configuration projects, each with a stack running as a docker compose service. Scaling horizontally would be painful, and, also having just come back to it after a long time, it strikes me as clunky to work with and deploy at present. Moving into 'garrison' is planned too, and my thinking on migrating to docker swarm was that it would be a step closer to deploying on a generic cluster or cloud, even if for now it is just on a dedicated cluster of VMs. Like you said we have a few examples of this already (e.g. Valkyrie, Seaice Analysis Tool), and at the very least would let us go from 2 VM configuration repositories to 1, and I think make future deployments somewhat simpler. Just my impressions for low-hanging fruit improvements, but I'm definitely open to ideas.

**Comment by wallinb** [comment]
On further thought, I think it is unnecessary to maintain a separate fork at this point.

**Pull request closed without merging**
